language: cpp
env:
  global:
    - DEPS=""
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8
      env:
        - DEPS="${DEPS} llvm@3.7"
        - LLVM_DIR=/usr/local/opt/llvm@3.7/lib/llvm-3.7/share/llvm/cmake/
    - os: linux
      compiler: g++
      root: required
      services:
        - docker
      env:
        - DIST=xenial

  allow_failures:
    - os: osx

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install ${DEPS}; fi
  - if [ $TRAVIS_OS_NAME = linux]; then
        docker build -f docker/build/${xenial}.Dockerfile -t hobbes:build; 
        docker run -it -v ${PWD}/..:/src build;
    fi


script:
  - if [ $TRAVIS_OS_NAME = osx   ]; then mkdir build && cd build/ && cmake .. && make  && make test; fi
  - if [ $TRAVIS_OS_NAME = linxu ]; then

branches:
  only:
    - master
    - travis
